// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Drug is the predicate function for drug builders.
type Drug func(*sql.Selector)

// RegisterStore is the predicate function for registerstore builders.
type RegisterStore func(*sql.Selector)

// Requisition is the predicate function for requisition builders.
type Requisition func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
