// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/Admin/app/ent/drug"
	"github.com/facebookincubator/ent/dialect/sql"
)

// Drug is the model entity for the Drug schema.
type Drug struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DrugQuery when eager-loading is set.
	Edges DrugEdges `json:"edges"`
}

// DrugEdges holds the relations/edges for other nodes in the graph.
type DrugEdges struct {
	// Requisitions holds the value of the requisitions edge.
	Requisitions []*Requisition
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// RequisitionsOrErr returns the Requisitions value or an error if the edge
// was not loaded in eager-loading.
func (e DrugEdges) RequisitionsOrErr() ([]*Requisition, error) {
	if e.loadedTypes[0] {
		return e.Requisitions, nil
	}
	return nil, &NotLoadedError{edge: "requisitions"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Drug) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // name
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Drug fields.
func (d *Drug) assignValues(values ...interface{}) error {
	if m, n := len(values), len(drug.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	d.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field name", values[0])
	} else if value.Valid {
		d.Name = value.String
	}
	return nil
}

// QueryRequisitions queries the requisitions edge of the Drug.
func (d *Drug) QueryRequisitions() *RequisitionQuery {
	return (&DrugClient{config: d.config}).QueryRequisitions(d)
}

// Update returns a builder for updating this Drug.
// Note that, you need to call Drug.Unwrap() before calling this method, if this Drug
// was returned from a transaction, and the transaction was committed or rolled back.
func (d *Drug) Update() *DrugUpdateOne {
	return (&DrugClient{config: d.config}).UpdateOne(d)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (d *Drug) Unwrap() *Drug {
	tx, ok := d.config.driver.(*txDriver)
	if !ok {
		panic("ent: Drug is not a transactional entity")
	}
	d.config.driver = tx.drv
	return d
}

// String implements the fmt.Stringer.
func (d *Drug) String() string {
	var builder strings.Builder
	builder.WriteString("Drug(")
	builder.WriteString(fmt.Sprintf("id=%v", d.ID))
	builder.WriteString(", name=")
	builder.WriteString(d.Name)
	builder.WriteByte(')')
	return builder.String()
}

// Drugs is a parsable slice of Drug.
type Drugs []*Drug

func (d Drugs) config(cfg config) {
	for _i := range d {
		d[_i].config = cfg
	}
}
