// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/Admin/app/ent/registerstore"
	"github.com/Admin/app/ent/requisition"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// RegisterStoreCreate is the builder for creating a RegisterStore entity.
type RegisterStoreCreate struct {
	config
	mutation *RegisterStoreMutation
	hooks    []Hook
}

// SetName sets the name field.
func (rsc *RegisterStoreCreate) SetName(s string) *RegisterStoreCreate {
	rsc.mutation.SetName(s)
	return rsc
}

// AddRequisitionIDs adds the requisitions edge to Requisition by ids.
func (rsc *RegisterStoreCreate) AddRequisitionIDs(ids ...int) *RegisterStoreCreate {
	rsc.mutation.AddRequisitionIDs(ids...)
	return rsc
}

// AddRequisitions adds the requisitions edges to Requisition.
func (rsc *RegisterStoreCreate) AddRequisitions(r ...*Requisition) *RegisterStoreCreate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return rsc.AddRequisitionIDs(ids...)
}

// Mutation returns the RegisterStoreMutation object of the builder.
func (rsc *RegisterStoreCreate) Mutation() *RegisterStoreMutation {
	return rsc.mutation
}

// Save creates the RegisterStore in the database.
func (rsc *RegisterStoreCreate) Save(ctx context.Context) (*RegisterStore, error) {
	if _, ok := rsc.mutation.Name(); !ok {
		return nil, &ValidationError{Name: "name", err: errors.New("ent: missing required field \"name\"")}
	}
	if v, ok := rsc.mutation.Name(); ok {
		if err := registerstore.NameValidator(v); err != nil {
			return nil, &ValidationError{Name: "name", err: fmt.Errorf("ent: validator failed for field \"name\": %w", err)}
		}
	}
	var (
		err  error
		node *RegisterStore
	)
	if len(rsc.hooks) == 0 {
		node, err = rsc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RegisterStoreMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			rsc.mutation = mutation
			node, err = rsc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(rsc.hooks) - 1; i >= 0; i-- {
			mut = rsc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, rsc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (rsc *RegisterStoreCreate) SaveX(ctx context.Context) *RegisterStore {
	v, err := rsc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (rsc *RegisterStoreCreate) sqlSave(ctx context.Context) (*RegisterStore, error) {
	rs, _spec := rsc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rsc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	rs.ID = int(id)
	return rs, nil
}

func (rsc *RegisterStoreCreate) createSpec() (*RegisterStore, *sqlgraph.CreateSpec) {
	var (
		rs    = &RegisterStore{config: rsc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: registerstore.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: registerstore.FieldID,
			},
		}
	)
	if value, ok := rsc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: registerstore.FieldName,
		})
		rs.Name = value
	}
	if nodes := rsc.mutation.RequisitionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   registerstore.RequisitionsTable,
			Columns: []string{registerstore.RequisitionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: requisition.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return rs, _spec
}
