// Code generated by entc, DO NOT EDIT.

package requisition

const (
	// Label holds the string label denoting the requisition type in the database.
	Label = "requisition"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAddedTime holds the string denoting the added_time field in the database.
	FieldAddedTime = "added_time"

	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeRegisterstore holds the string denoting the registerstore edge name in mutations.
	EdgeRegisterstore = "registerstore"
	// EdgeDrug holds the string denoting the drug edge name in mutations.
	EdgeDrug = "drug"

	// Table holds the table name of the requisition in the database.
	Table = "requisitions"
	// UserTable is the table the holds the user relation/edge.
	UserTable = "requisitions"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// RegisterstoreTable is the table the holds the registerstore relation/edge.
	RegisterstoreTable = "requisitions"
	// RegisterstoreInverseTable is the table name for the RegisterStore entity.
	// It exists in this package in order to avoid circular dependency with the "registerstore" package.
	RegisterstoreInverseTable = "register_stores"
	// RegisterstoreColumn is the table column denoting the registerstore relation/edge.
	RegisterstoreColumn = "registerstore_id"
	// DrugTable is the table the holds the drug relation/edge.
	DrugTable = "requisitions"
	// DrugInverseTable is the table name for the Drug entity.
	// It exists in this package in order to avoid circular dependency with the "drug" package.
	DrugInverseTable = "drugs"
	// DrugColumn is the table column denoting the drug relation/edge.
	DrugColumn = "drug_id"
)

// Columns holds all SQL columns for requisition fields.
var Columns = []string{
	FieldID,
	FieldAddedTime,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Requisition type.
var ForeignKeys = []string{
	"drug_id",
	"registerstore_id",
	"user_id",
}
