/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntRegisterStoreEdges,
    EntRegisterStoreEdgesFromJSON,
    EntRegisterStoreEdgesFromJSONTyped,
    EntRegisterStoreEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntRegisterStore
 */
export interface EntRegisterStore {
    /**
     * 
     * @type {EntRegisterStoreEdges}
     * @memberof EntRegisterStore
     */
    edges?: EntRegisterStoreEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntRegisterStore
     */
    id?: number;
    /**
     * Name holds the value of the "name" field.
     * @type {string}
     * @memberof EntRegisterStore
     */
    name?: string;
}

export function EntRegisterStoreFromJSON(json: any): EntRegisterStore {
    return EntRegisterStoreFromJSONTyped(json, false);
}

export function EntRegisterStoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntRegisterStore {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'edges': !exists(json, 'edges') ? undefined : EntRegisterStoreEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function EntRegisterStoreToJSON(value?: EntRegisterStore | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'edges': EntRegisterStoreEdgesToJSON(value.edges),
        'id': value.id,
        'name': value.name,
    };
}


