/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntRequisitionEdges,
    EntRequisitionEdgesFromJSON,
    EntRequisitionEdgesFromJSONTyped,
    EntRequisitionEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntRequisition
 */
export interface EntRequisition {
    /**
     * AddedTime holds the value of the "added_time" field.
     * @type {string}
     * @memberof EntRequisition
     */
    addedTime?: string;
    /**
     * 
     * @type {EntRequisitionEdges}
     * @memberof EntRequisition
     */
    edges?: EntRequisitionEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntRequisition
     */
    id?: number;
}

export function EntRequisitionFromJSON(json: any): EntRequisition {
    return EntRequisitionFromJSONTyped(json, false);
}

export function EntRequisitionFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntRequisition {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'addedTime': !exists(json, 'added_time') ? undefined : json['added_time'],
        'edges': !exists(json, 'edges') ? undefined : EntRequisitionEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntRequisitionToJSON(value?: EntRequisition | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'added_time': value.addedTime,
        'edges': EntRequisitionEdgesToJSON(value.edges),
        'id': value.id,
    };
}


